import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's github repository
*/
`;

const prod = process.argv[2] === "production";
const outDir = "dist";

// manifest.json/styles.css are authored at the repo root (not bundled by
// esbuild) but Obsidian needs them sitting next to main.js — copy them into
// dist/ after every build (including each watch-mode rebuild) so dist/ is
// always a complete, drop-in plugin folder on its own.
const copyStaticFilesPlugin = {
	name: "copy-static-files",
	setup(build) {
		build.onEnd(() => {
			fs.mkdirSync(outDir, { recursive: true });
			for (const file of ["manifest.json", "styles.css"]) {
				fs.copyFileSync(file, path.join(outDir, file));
			}
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outDir}/main.js`,
	minify: prod,
	plugins: [copyStaticFilesPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
